# Generated by Django 4.2.4 on 2023-09-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusphere_app', '0007_student_contact_number_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default='1990-01-01'),
        ),
    ]
