# Generated by Django 4.2.4 on 2023-09-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusphere_app', '0010_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
