# Generated by Django 4.2.4 on 2023-09-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edusphere_app', '0011_alter_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
