# Generated by Django 4.2.4 on 2023-09-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusphere_app', '0015_remove_course_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
